import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import * as secp from "noble-secp256k1"

export default function Home() {
  const privateKey = "6b911fd37cdf5c81d4c0adb1ab7fa822ed253ab0ad9aa18d77257c88b29b718e";
  const messageHash = "a33321f98e4ff1c283c76998f14f57447545d339b3db534c6d886decb4209f28";
  const publicKey = secp.getPublicKey(privateKey);

  return (
    <div className={styles.container}>
      <Head>
        <title>Sheesh Coin</title>
        <meta name="description" content="Generated by nibnalin and adhyyan" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div class="form-control">
          <label class="label">
            <span class="label-text">Private Key</span> 
            <a href="#" class="label-text-alt">
                  Generate private key
                </a>
          </label> 
          <input type="text" placeholder="privatekey" class="input input-primary input-bordered" />
        </div> 
        <div class="form-control">
          <label class="label">
            <span class="label-text">Public Key</span>
          </label> 
          <input type="text" placeholder="username" class="input input-secondary input-bordered" />
        </div> 
        <div class="form-control">
          <label class="label">
            <span class="label-text">Public key to</span>
          </label> 
          <input type="text" placeholder="username" class="input input-accent input-bordered" />
        </div>
        <div class="form-control">
          <label class="label">
            <span class="label-text">Amount</span>
          </label> 
          <input type="text" placeholder="username" class="input input-accent input-bordered" />
        </div>
        <div class="form-control">
          <label class="label">
            <span class="label-text">Fee</span>
          </label> 
          <input type="text" placeholder="username" class="input input-accent input-bordered" />
        </div>
        <div class="form-control">
          <label class="label">
            <span class="label-text">Nonce</span>
          </label> 
          <input type="text" placeholder="username" class="input input-accent input-bordered" />
        </div>
        <div class="form-control">
          <label class="label">
            <span class="label-text">Signature</span>
          </label> 
          <input type="text" placeholder="username" class="input input-accent input-bordered" />
        </div>
      </main>

      <footer className={styles.footer}>
          Made by nibnalin and adhyyan.
      </footer>
    </div>
  )
}
